[build]
  base = ""
  command = "python3 -m pip install -r requirements.txt && python3 manage.py collectstatic --noinput && python3 manage.py migrate"
  publish = "staticfiles"

[context.production.environment]
  PYTHON_VERSION = "3.13"

[[plugins]]
  package = "@netlify/plugin-python"
