# Generated by Django 5.2.6 on 2025-09-20 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0003_alter_parent_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='MechanicalFirstYearStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HomePage.student')),
            ],
            options={
                'verbose_name': 'Mechanical First Year Student',
                'verbose_name_plural': 'Mechanical First Year Students',
            },
        ),
    ]
