# Generated by Django 5.2.6 on 2025-09-20 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0004_mechanicalfirstyearstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
        ),
        migrations.CreateModel(
            name='MechanicalFourthYearStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HomePage.student')),
            ],
            options={
                'verbose_name': 'Mechanical Fourth Year Student',
                'verbose_name_plural': 'Mechanical Fourth Year Students',
            },
        ),
        migrations.CreateModel(
            name='MechanicalSecondYearStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HomePage.student')),
            ],
            options={
                'verbose_name': 'Mechanical Second Year Student',
                'verbose_name_plural': 'Mechanical Second Year Students',
            },
        ),
        migrations.CreateModel(
            name='MechanicalThirdYearStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HomePage.student')),
            ],
            options={
                'verbose_name': 'Mechanical Third Year Student',
                'verbose_name_plural': 'Mechanical Third Year Students',
            },
        ),
    ]
