# Generated by Django 5.2.6 on 2025-09-20 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0005_parent_gender_student_age_student_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricalFirstYearStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HomePage.student')),
            ],
            options={
                'verbose_name': 'Electrical First Year Student',
                'verbose_name_plural': 'Electrical First Year Students',
            },
        ),
        migrations.CreateModel(
            name='ElectricalFourthYearStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HomePage.student')),
            ],
            options={
                'verbose_name': 'Electrical Fourth Year Student',
                'verbose_name_plural': 'Electrical Fourth Year Students',
            },
        ),
        migrations.CreateModel(
            name='ElectricalSecondYearStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HomePage.student')),
            ],
            options={
                'verbose_name': 'Electrical Second Year Student',
                'verbose_name_plural': 'Electrical Second Year Students',
            },
        ),
        migrations.CreateModel(
            name='ElectricalThirdYearStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HomePage.student')),
            ],
            options={
                'verbose_name': 'Electrical Third Year Student',
                'verbose_name_plural': 'Electrical Third Year Students',
            },
        ),
    ]
