# Generated by Django 5.2.6 on 2025-09-22 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0010_leave_notification_result_timetable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date']},
        ),
    ]
